### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by ozne1** [UltimMC/Launcher#316]
### Description of bug

![image](https://github.com/UltimMC/Launcher/assets/30633394/8e29a3c6-9727-4484-afb1-d85b960a5b28)
this image appears when trying to download

### Steps to reproduce

try to download

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by zebn0710** [comment]
im having the same issue

**Comment by Labnann** [comment]
It seems installation of Qt for win32-5152 in the workflow is currently broken, failing to complete automatic build. (Because openssl-x86 tool is missing?)

Workaround: try getting your artifact from GitHub actions.


The current build can be availed here:
https://github.com/UltimMC/Launcher/actions/runs/6843330274

Check under the artifacts section. :)

**Comment by KienPC1234** [comment]
Link For Windows Here:
https://github.com/UltimMC/Launcher/issues/319

**Comment by Raif1** [comment]
Can anyone tell me why the linux build is getting flagged in virustotal?
![image](https://github.com/UltimMC/Launcher/assets/93464125/57168ea9-1b24-477e-b2d0-57034972abee)

**Comment by create-juicey-app** [comment]
> Can anyone tell me why the linux build is getting flagged in virustotal?
> ![image](https://github.com/UltimMC/Launcher/assets/93464125/57168ea9-1b24-477e-b2d0-57034972abee)
> 

If it's only one trigger, that means its a false positive, if it is really a virus, multiple antivirus software would have been triggered too
